### ISSUE TITLE
Support drag-and-drop onto the table in the edit window.

### ISSUE THREAD

**Issue by natechan** [bignerdranch/DemoMonkey#7]
Requested by @hillegass.

The user should be able to drag text (out of Xcode, for example) into DemoMonkey.  The user should be able to do drag and drop into the table view in the edit window.

**Comment by lyricsboy** [comment]
Agreed, this would be a great feature. :+1:

**Comment by lyricsboy** [comment]
It's such a great feature, in fact, that it's already implemented. :apple: :clap:

**Comment by natechan** [comment]
:tophat: :astonished: :clap:
